Corrige l'apparence de :magicien: :)
zestedesavoir/documents-communication pull request #39
Opened 2020-05-26 06:18 UTC by arobase-che

Un PR qui corrige : 

 - Les yeux et le sourire de :)
 - Le sourire de :magicien:

Bon, j'ai modifié la version non optimisé. Il faudrait passé un coup de svgo. J'ai pas eu le temps de regarder tout en détails, si c'est fait automatiquement ou quoi.

Ce que je sais c'est que j'ai bien modifié les bon SVG en limitant les modifications.

Maintenant il faut juste s'assurer de comment et comment sont  faites les version optimisées.

2020-05-28 02:36 UTC, arobase-che commented
Ok donc d'après moi, l'optimisation est effectuée au dernier moment.
En bref, c'est sur le serveur de ZdS qu'il va falloir le faire.

Donc la PR est prêt à être mergée.

2020-05-28 13:36 UTC, A-312 commented on emoticones/clemojiv3/svg/smile.svg
> +      <path id="g32_4_" fill="#9A2400" d="m 13.130253,33.12632 a 0.4232,0.4232 0 0 0 0.296,-0.7256 5.4688,5.4688 0 0 0 -3.8408004,-1.5696 c -1.44,0 -2.804,0.556 -3.84,1.568 a 0.424,0.424 0 0 0 0.592,
Q/A :

![](https://raw.githubusercontent.com/zestedesavoir/documents-communication/8efe11fe5ffa05a8197be83a808c73f9e08ada6a/emoticones/clemojiv3/svg/magicien.svg)

![](https://raw.githubusercontent.com/zestedesavoir/documents-communication/8efe11fe5ffa05a8197be83a808c73f9e08ada6a/emoticones/clemojiv3/svg/smile.svg) attendu : ![image](https://user-images.githubusercontent.com/18501150/83148032-bce9e480-a0f8-11ea-8bf9-d650972c789c.png) (Les feuilles: OK, la bouche : ne correspond pas)

2020-05-28 13:36 UTC, A-312 requested changes

2020-05-28 13:36 UTC, A-312 commented on emoticones/clemojiv3/svg/smile.svg
> +      <path id="g32_4_" fill="#9A2400" d="m 13.130253,33.12632 a 0.4232,0.4232 0 0 0 0.296,-0.7256 5.4688,5.4688 0 0 0 -3.8408004,-1.5696 c -1.44,0 -2.804,0.556 -3.84,1.568 a 0.424,0.424 0 0 0 0.592,
Q/A :

![](https://raw.githubusercontent.com/zestedesavoir/documents-communication/8efe11fe5ffa05a8197be83a808c73f9e08ada6a/emoticones/clemojiv3/svg/magicien.svg)

![](https://raw.githubusercontent.com/zestedesavoir/documents-communication/8efe11fe5ffa05a8197be83a808c73f9e08ada6a/emoticones/clemojiv3/svg/smile.svg) attendu : ![image](https://user-images.githubusercontent.com/18501150/83148032-bce9e480-a0f8-11ea-8bf9-d650972c789c.png) (Les feuilles: OK, la bouche : ne correspond pas)

2020-05-28 16:51 UTC, arobase-che commented on emoticones/clemojiv3/svg/smile.svg
> +      <path id="g32_4_" fill="#9A2400" d="m 13.130253,33.12632 a 0.4232,0.4232 0 0 0 0.296,-0.7256 5.4688,5.4688 0 0 0 -3.8408004,-1.5696 c -1.44,0 -2.804,0.556 -3.84,1.568 a 0.424,0.424 0 0 0 0.592,
J'ai fait la modification. Ça devrait coïncider parfaitement.

Je trouvais l'un trop haut, l'autre trop bas.

2020-05-29 13:11 UTC, A-312 reviewed
# Q/A : 

![](https://raw.githubusercontent.com/zestedesavoir/documents-communication/7bcffec1a00639fda12da4ca436be07e02e51860/emoticones/clemojiv3/svg/magicien.svg) et ![](https://raw.githubusercontent.com/zestedesavoir/documents-communication/7bcffec1a00639fda12da4ca436be07e02e51860/emoticones/clemojiv3/svg/smile.svg) ok pour moi :)

2020-05-29 13:12 UTC, A-312 commented
@arobase-che C'est voulu la différence des yeux entres les deux emotes ? On garde pas les yeux du magiciens ?

2020-05-29 13:18 UTC, arobase-che commented
Ben il y a des gens que ça génait les yeux ovales.
Je trouve perso que ça gène pas.

Comme les remarques avaient été faite uniquement pour :)
J'ai modifié que celui-ci.

J'aime bien les yeux ovales mais c'est vrai que pour le :) ça peut faire un peu bizarre. C'est ce que j'ai pensé en éditant les deux smiley.

2020-05-29 13:20 UTC, arobase-che commented
J'ai tenté de bien les alignés pour pas que ça soit trop flagrant.

Du coup, je merge, puisque tu es Ok.

Merci ! ^^

2020-05-29 13:20 UTC, merged

2020-09-19 13:45 UTC, Situphen commented
@arobase-che Si tu as le temps et l'envie, il faudrait faire la même chose avec le smiley `:ange:` :) [Demandé sur le forum](https://zestedesavoir.com/forums/sujet/14115/nouveau-graphisme-des-smileys/?page=2#p226129)

2020-09-19 14:24 UTC, arobase-che commented
Pas de soucis. ^^

Je suis en vacances là. Mardi soir je m'en occupe. ^^